### ISSUE TITLE
Issue with connecting to LC7001

### ISSUE THREAD

**Issue by surfahboy21** [sbozarth/homebridge-lc7001#11] opened 2021-01-21 01:24 UTC
Hello,

I apologize in advance if this has been answered already. I'm new to Homebridge (this is the first plugin that I've installed, in fact) and I tried to read through some of the other issues / comments here first before posting, but nothing seemed to discuss my exact situation. So I decided to submit a new issue in hopes that someone (whether it be the developer or other users) might be able to explain what's happening and what I can do to fix this.

First, for reference, here is the information about my system (in case people might find it useful or necessary to further troubleshoot the problem described below): I'm running Homebridge version 1.1.7 on an (always-on) iMac, the Node version is 14.15.3 and the Npm version is 6.14.9, the plugin version that I've installed is 1.1.1 and I have not made any changes to the plugin's settings options during installation (other than providing the LC7001 password that I set up using Legrand's iOS app), and finally the LC7001's firmware version is 4.2.1-9-g1eb5.

So now, after installing the plugin successfully, I restarted Homebridge and then saw this....

[1/20/2021, 2:55:08 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/20/2021, 2:55:08 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 4485
[1/20/2021, 2:55:08 PM] Loaded config.json with 0 accessories and 2 platforms.
[1/20/2021, 2:55:08 PM] ---
[1/20/2021, 2:55:08 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/20/2021, 2:55:08 PM] Registering platform 'homebridge-config-ui-x.config'
[1/20/2021, 2:55:08 PM] ---
[1/20/2021, 2:55:08 PM] Loaded plugin: homebridge-lc7001@1.1.1
[1/20/2021, 2:55:08 PM] Registering platform 'homebridge-lc7001.LC7001'
[1/20/2021, 2:55:08 PM] ---
[1/20/2021, 2:55:08 PM] Loading 2 platforms...
[1/20/2021, 2:55:08 PM] [Config] Initializing config platform...
[1/20/2021, 2:55:08 PM] [Config] Running in Service Mode
[1/20/2021, 2:55:08 PM] [LC7001] Initializing LC7001 platform...
[1/20/2021, 2:55:08 PM] [LC7001] Platform initializing....
[1/20/2021, 2:55:08 PM] [LC7001] Connecting to LC7001....
[1/20/2021, 2:55:08 PM] [LC7001] Platform initialized.

Soon after that, the following errors began to appear in my log....

[1/20/2021, 3:09:03 PM] [LC7001] Connecting to LC7001....
[1/20/2021, 3:09:03 PM] [LC7001] Connection to LC7001 established.
[1/20/2021, 3:09:03 PM] [LC7001] Unable to parse segment: 9DD3008738E7575F
[1/20/2021, 3:09:03 PM] [LC7001] Unable to parse segment: 0F5EFE87BA6A48FA
[1/20/2021, 3:09:03 PM] [LC7001] Unable to parse segment:  0026EC02F9D2
[1/20/2021, 3:09:30 PM] [LC7001] Error on LC7001 connection: Error: read ECONNRESET
[1/20/2021, 3:09:30 PM] [LC7001] Connection to LC7001 closed due to error. Waiting 30 seconds to reconnect....

This continues to happen every 30 seconds.

If anyone can provide insight / assistance on how to fix this, I would greatly appreciate it. And of course, if there's more information that I can provide in order to better describe the situation, please let me know. Thanks in advance!

**Comment by fsalum** [comment] 2021-01-21 01:33
Looks like the new firmware update 4:2:1-9 breaks this plugin.

I'm on 4.1.2-7 and it just requested me to update the firmware but I didn't accept.

**Comment by surfahboy21** [comment] 2021-01-21 02:58
> Looks like the new firmware update 4:2:1-9 breaks this plugin.
> 
> I'm on 4.1.2-7 and it just requested me to update the firmware but I didn't accept.

Hey thanks for replying / providing feedback. I don't suppose you know of a way to downgrade it? I just bought this and it came with this firmware version.

**Comment by fsalum** [comment] 2021-01-21 03:03
Downgrade is not possible. I sent an email to my contacts at Legrand asking if the authentication steps changed in the new version. I will update here for @sbozarth to take a look once I get some response from them.

**Comment by sbozarth** [comment] 2021-01-21 03:12
surfahboy21: Can you get homebridge into debug mode? This is done by running homebridge with the -D option.

The plugin will produce a LOT of debugging information. I am mostly interested in everything from when it connects to the LC7001 to when it prints the error you received.

The documentation we received said you are supposed to get a 32-byte hex string followed by a 12-byte MAC address. You receive 32 bytes followed by 12, but there is some kind of separation in the middle of your 32 bytes. Getting the debug information will go a long way.

Also, do you have the ability to capture packets between your LC7001 and the LCA (iOS app)? This might be necessary if simply concatenating the two 16-byte strings together does not solve the problem.

It will help us if you get the password to something you do not mind sharing...like "homebridge". You can change it back when we get it fixed or give up trying.

**Comment by thk-socal** [comment] 2021-01-21 04:08
Interesting, my LC7001 was just updated to this version and I am running just fine. I have had mine for awhile though and there is still not authentication set in my device.

**Comment by sbozarth** [comment] 2021-01-21 04:21
cscott365: Lack of authentication will keep it working just fine. Mine does not have authentication either, which is why I have trouble with these authentication problems--I can't test them. The plugin was broken for like a year because I was blissfully ignorant of authentication.

**Comment by surfahboy21** [comment] 2021-01-21 04:37
Hi everyone. Thank you for responding so quickly. @sbozarth I copied / pasted below what showed up in the log after I turned debugging on...

[1/20/2021, 6:31:59 PM] Homebridge is running on port 51844.
[1/20/2021, 6:31:59 PM] [LC7001] Connection to LC7001 established.
[1/20/2021, 6:31:59 PM] [LC7001] -->IP Version:       IPv4
[1/20/2021, 6:31:59 PM] [LC7001] -->IP Address:       192.168.127.143
[1/20/2021, 6:31:59 PM] [LC7001] -->TCP Port:         2112
[1/20/2021, 6:31:59 PM] [LC7001] -->Local IP Address: 192.168.127.131
[1/20/2021, 6:31:59 PM] [LC7001] -->Local TCP Port:   57298
[1/20/2021, 6:31:59 PM] [LC7001] Connection to LC7001 ready for use.
[1/20/2021, 6:31:59 PM] [LC7001] Data received from LC7001 (stringified): "Hello V1 \u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Processing data received from LC7001....
[1/20/2021, 6:31:59 PM] [LC7001] Starting buffer: ""
[1/20/2021, 6:31:59 PM] [LC7001] Data received: "Hello V1 \u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Delimiter: "\u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Segments received: 2
[1/20/2021, 6:31:59 PM] [LC7001] --> 1 : "Hello V1 "
[1/20/2021, 6:31:59 PM] [LC7001] --> 2 : ""
[1/20/2021, 6:31:59 PM] [LC7001] Processing segment: 1
[1/20/2021, 6:31:59 PM] [LC7001] Checking if segment is good JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not good JSON. Checking if segment is an authentication message....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is an authentication message. This LC7001 requires authentication.
[1/20/2021, 6:31:59 PM] [LC7001] Processing segment: 2
[1/20/2021, 6:31:59 PM] [LC7001] Segment has length 0; skipping.
[1/20/2021, 6:31:59 PM] [LC7001] Processing Receive Queue....
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue length: 0
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue empty; nothing to do.
[1/20/2021, 6:31:59 PM] [LC7001] Data received from LC7001 (stringified): "48F8962264F286CA"
[1/20/2021, 6:31:59 PM] [LC7001] Processing data received from LC7001....
[1/20/2021, 6:31:59 PM] [LC7001] Starting buffer: ""
[1/20/2021, 6:31:59 PM] [LC7001] Data received: "48F8962264F286CA"
[1/20/2021, 6:31:59 PM] [LC7001] Delimiter: "\u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Segments received: 1
[1/20/2021, 6:31:59 PM] [LC7001] --> 1 : "48F8962264F286CA"
[1/20/2021, 6:31:59 PM] [LC7001] Processing segment: 1
[1/20/2021, 6:31:59 PM] [LC7001] Checking if segment is good JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not good JSON. Checking if segment is an authentication message....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not an authentication message. Checking for undelimited JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Skipping....
[1/20/2021, 6:31:59 PM] [LC7001] Processing Receive Queue....
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue length: 0
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue empty; nothing to do.
[1/20/2021, 6:31:59 PM] [LC7001] Data received from LC7001 (stringified): "C4D4585E464116A9"
[1/20/2021, 6:31:59 PM] [LC7001] Processing data received from LC7001....
[1/20/2021, 6:31:59 PM] [LC7001] Starting buffer: ""
[1/20/2021, 6:31:59 PM] [LC7001] Data received: "C4D4585E464116A9"
[1/20/2021, 6:31:59 PM] [LC7001] Delimiter: "\u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Segments received: 1
[1/20/2021, 6:31:59 PM] [LC7001] --> 1 : "C4D4585E464116A9"
[1/20/2021, 6:31:59 PM] [LC7001] Unable to parse segment: 48F8962264F286CA
[1/20/2021, 6:31:59 PM] [LC7001] Unable to parse segment: C4D4585E464116A9
[1/20/2021, 6:31:59 PM] [LC7001] Unable to parse segment:  0026EC02F9D2
[1/20/2021, 6:31:59 PM] [LC7001] Processing segment: 1
[1/20/2021, 6:31:59 PM] [LC7001] Checking if segment is good JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not good JSON. Checking if segment is an authentication message....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not an authentication message. Checking for undelimited JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Skipping....
[1/20/2021, 6:31:59 PM] [LC7001] Processing Receive Queue....
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue length: 0
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue empty; nothing to do.
[1/20/2021, 6:31:59 PM] [LC7001] Data received from LC7001 (stringified): " 0026EC02F9D2"
[1/20/2021, 6:31:59 PM] [LC7001] Processing data received from LC7001....
[1/20/2021, 6:31:59 PM] [LC7001] Starting buffer: ""
[1/20/2021, 6:31:59 PM] [LC7001] Data received: " 0026EC02F9D2"
[1/20/2021, 6:31:59 PM] [LC7001] Delimiter: "\u0000"
[1/20/2021, 6:31:59 PM] [LC7001] Segments received: 1
[1/20/2021, 6:31:59 PM] [LC7001] --> 1 : " 0026EC02F9D2"
[1/20/2021, 6:31:59 PM] [LC7001] Processing segment: 1
[1/20/2021, 6:31:59 PM] [LC7001] Checking if segment is good JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not good JSON. Checking if segment is an authentication message....
[1/20/2021, 6:31:59 PM] [LC7001] Segment is not an authentication message. Checking for undelimited JSON....
[1/20/2021, 6:31:59 PM] [LC7001] Skipping....
[1/20/2021, 6:31:59 PM] [LC7001] Processing Receive Queue....
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue length: 0
[1/20/2021, 6:31:59 PM] [LC7001] Receive Queue empty; nothing to do.
[1/20/2021, 6:32:00 PM] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8581
[1/20/2021, 6:32:15 PM] [LC7001] Error on LC7001 connection: Error: read ECONNRESET
[1/20/2021, 6:32:15 PM] [LC7001] Connection to LC7001 closed due to error. Waiting 30 seconds to reconnect....
[1/20/2021, 6:32:45 PM] [LC7001] Connecting to LC7001....
[1/20/2021, 6:32:45 PM] [LC7001] TCP Options:
[1/20/2021, 6:32:45 PM] [LC7001] --> host: LCM1.local
[1/20/2021, 6:32:45 PM] [LC7001] --> port: 2112
[1/20/2021, 6:32:45 PM] [LC7001] --> localAddress: undefined
[1/20/2021, 6:32:45 PM] [LC7001] --> localPort: undefined
[1/20/2021, 6:32:45 PM] [LC7001] --> family: undefined
[1/20/2021, 6:32:45 PM] [LC7001] Connection to LC7001 established.

And then it basically repeated from there...again in 30 second intervals.

As far as capturing packets, I'm afraid that I don't even know what that means...sorry! But I'm certainly willing to give it a try if you or someone wouldn't mind explaining the process to me. Please let me know how else I can try to help. Thank you everyone!

**Comment by surfahboy21** [comment] 2021-01-21 04:41
> It will help us if you get the password to something you do not mind sharing...like "homebridge". You can change it back when we get it fixed or give up trying.

Sorry, @sbozarth, I just realized I didn't respond to this part of your comment. I do have the password to homebridge. It's just the default, "admin" right now because I didn't get around to changing it. Literally learned about homebridge and got it set up on Monday. So yeah, totally new at all of this! :)

**Comment by sbozarth** [comment] 2021-01-21 04:43
I meant set the LC7001 authentication password to "homebridge." Sounds like you're referring to the default password for homebridge-UI, which is "admin." I just don't want you to expose your LC7001 password.

**Comment by surfahboy21** [comment] 2021-01-21 04:45
> I meant set the LC7001 authentication password to "homebridge." Sounds like you're referring to the default password for homebridge-UI, which is "admin." I just don't want you to expose your LC7001 password.

Oops. I see what you mean now. Haha, I'll change that temporarily to "homebridge" for the purposes of troubleshooting. Thank you for the clarification.

**Comment by sbozarth** [comment] 2021-01-21 05:46
I think you may have found a bug. Try this:

Stop homebridge.
Change line 306 of homebridge-lc7001/lib/lc7001.js from:
    if (index = splitBuffer.length - 1)
to
   if (index == (splitBuffer.length - 1))
Restart homebridge

You can modify it while homebridge is running and then restart it, but stopping is the better option.

What's going on is that IF statement commits anything that the plugin cannot understand from the receive buffer into a temporary holding area that gets prepended to the next transmission. Most installations seem to not ever use this, but you're getting a LOT of small segments. Maybe it has something to do with MacOS.

The bug is the single = sign. In JavaScript that is an assignment, not a test.

**Comment by sbozarth** [comment] 2021-01-21 05:46
Oh, there is a { at the end of that line. Leave it there.

**Comment by surfahboy21** [comment] 2021-01-21 06:28
Wow thanks for all the quick work / responses. I'm trying to google how to find or access the file lc7001.js on my hard drive because I don't see a way to access it directly from the Homebridge UI that I'm using (web browser pointed to localhost URL). Any thoughts on how to find the file in question?

**Comment by sbozarth** [comment] 2021-01-21 06:47
I just published 1.1.2 to NPM. You should be able to do an update, but I'm not entirely clear how to get homebrige-UI to check for updates. I happened to have another patch that I needed to push out and I'm pretty confident in the change I made for you.

I'm not clear at all on where the files would be on MacOS, so this seems easier.

**Comment by surfahboy21** [comment] 2021-01-21 06:54
You are AWESOME. It works now. Thanks so much for your help and patience!!

**Comment by surfahboy21** [comment] 2021-01-22 20:37
Hi again. Sorry for the trouble but now this is happening randomly / sporadically throughout the day....

[1/22/2021, 8:59:18 AM] [LC7001] Connection to LC7001 has been inactive for 30 seconds. Destroying connection....
[1/22/2021, 8:59:18 AM] [LC7001] Connection to LC7001 closed. Reconnecting....
[1/22/2021, 8:59:18 AM] [LC7001] Connecting to LC7001....
[1/22/2021, 8:59:23 AM] [LC7001] Error on LC7001 connection: Error: getaddrinfo ENOTFOUND LCM1.local
[1/22/2021, 8:59:23 AM] [LC7001] Connection to LC7001 closed due to error. Waiting 30 seconds to reconnect....
[1/22/2021, 8:59:53 AM] [LC7001] Connecting to LC7001....
[1/22/2021, 8:59:53 AM] [LC7001] Connection to LC7001 established.
[1/22/2021, 8:59:56 AM] [LC7001] Successfully authenticated to LC7001. Initializing LC7001....

Admittedly, after things began working 2 days ago, I turned off the debug mode. So there isn't as much log detail as you'd probably want. But I just turned it back on so if the same error occurs again, I'll follow up with another post so that you have more specific information. Thanks in advance.

**Comment by sbozarth** [comment] 2021-01-22 21:02
The inactive errors happen every so often. The LC7001 sends a PING message regularly. Sometimes, the plugin would go to set a light state and then error out because the connection had actually failed in the background. So, I just utilized the Node.js inactivity timeout to destroy dead connections and reconnect.

So, the first part (8:59:18) is relatively normal. The second part (8:59:23) is not so normal. It suggests that your Mac failed to resolve the LCM1.local mDNS name. mDNS works by essentially broadcasting a request for LCM1 and the LC7001 is supposed to respond with its IP address. If you're familiar with ARP, basically the same concept. It does not resolve at 8:59:23, but does 30 seconds later at 8:59:56.

This is not something I can fix. I wouldn't worry too much about the first error. You can shorten the timeout so it resets faster -- either less time before it destroys the connection or less time before it tries to reestablish. You're down for essentially 1m30s if the mDNS error happens every time. You could cut that out by specifying the IP address in the config. To shorten the times, you either have to modify the code (and find it) or I have convert those values into config values, which would be a worthwhile project.

**Comment by sbozarth** [comment] 2021-01-24 04:15
I created configuration settings for the timeout and retry times. Republished as v1.2.0.

TCP Timeout is the number of seconds of inactivity between the plugin and the LC7001 before the connection is deemed dead.

TCP Retry is the number of seconds the plugin waits before trying to reconnect to the LC7001 after an error.

**Comment by thk-socal** [comment] 2021-01-25 17:24
Bigger question, how do I send you money for coffee or something? Really appreciate all the work you do on this as a side gig and want to honor that. Made it so easy for me to move to locally controlled devices and off of the cloud controlled suff which not only preserves more of my privacy, but allows for much quicker response. Great work!

**Comment by sbozarth** [comment] 2021-01-25 18:26
I appreciate the offer, but your acknowledgment is thanks enough. Obviously, I wrote this for myself and just wanted to share. I enjoy the odds and ends that crop up after the fact — gives me something else to do on occasion. The problems also show people are using this.

**Comment by arianf** [comment] 2021-07-02 03:39
@sbozarth I'm thinking about buying a HOOBS just for this plugin, my house I bought has 100% adorne light switches. It seems like this issue is resolved? Is there a reason this issue is still open?

**Comment by sbozarth** [comment] 2021-07-02 06:28
> @sbozarth I'm thinking about buying a HOOBS just for this plugin, my house I bought has 100% adorne light switches. It seems like this issue is resolved? Is there a reason this issue is still open?

I do not think there is. I will close it.

You say you bought the house. If it came with Adorne switches, I will point out that just having Adorne switches does not necessarily mean they will work with an LC7001. If you already have an LC7001 and it works, you're good. Otherwise, they have to be the RF version of the switch to work.

**Closed as completed by sbozarth** 2021-07-02 06:28 UTC

**Comment by arianf** [comment] 2021-07-02 06:33
Yes, I took off the faceplates and confirmed the developer of the house placed WiFi ready adorne dimmers only in the bedrooms, and regular non-WiFi ones in the living room and hallways. Will test the HOOBS + LC7001 with those dimmers before upgrading the rest of the dimmers to WiFi. Thanks for the quick response!

**Comment by sbozarth** [comment] 2021-07-02 06:41
No problem.

On a side note, a birdie told me that the RF Adorne switches are being replaced later this month with Zigbee switches, that will natively support HomeKit. The RF stuff will be sold through September.

You might want to consider holding out if the number of new RF switches you'd buy is substantial or you just don't want to deal with HOOBS.

**Comment by arianf** [comment] 2021-07-02 06:47
Oh wow! That’s amazing! Thanks for the heads up! With only 3 WiFi dimmers and 19 non-WiFi dimmers the wait will definitely be worth it
